[package]
name = "cdn_publish_cli"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "env"] }
http = "1"
secret_rs.workspace = true
typed-builder.workspace = true
url.workspace = true

[dev-dependencies]
rstest.workspace = true
