name: Integration Tests

on:
  workflow_call:
    inputs:
      node-version:
        default: 18.x
        required: false
        type: string
    secrets:
      storage_access_key:
        required: true
      storage_zone_name:
        required: true
      storage_base_url:
        required: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true

      - name: Install
        run: yarn install --immutable

      - name: Run integration tests
        run: yarn test:integration
        env:
          CDN_STORAGE_ACCESS_KEY: ${{ secrets.storage_access_key }}
          CDN_STORAGE_ZONE_NAME: ${{ secrets.storage_zone_name }}
          CDN_STORAGE_BASE_URL: ${{ secrets.storage_base_url }}
