name: Main

env:
  context: "./"
  cache-name: cache-release
  node-version: 18.x

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "package.json"
      - "yarn.lock"
      - "src/**"
      - "tests/**"
      - ".docker/**"

jobs:
  prepare:
    uses: mia-platform/cdn-publish/.github/workflows/prepare.yml@main

  checks:
    needs:
      - prepare
    uses: mia-platform/cdn-publish/.github/workflows/checks.yml@main

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    needs:
      - prepare
    uses: mia-platform/cdn-publish/.github/workflows/unit-tests.yml@main
    with:
      node-version: ${{ matrix.node-version }}

  integration-tests:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    needs:
      - prepare
    uses: mia-platform/cdn-publish/.github/workflows/integration-tests.yml@main
    with:
      node-version: ${{ matrix.node-version }}
    secrets:
      storage_access_key: ${{ secrets.CDN_STORAGE_ACCESS_KEY }}
      storage_zone_name: ${{ secrets.CDN_STORAGE_ZONE_NAME }}
      storage_base_url: ${{ secrets.CDN_STORAGE_BASE_URL }}

  release-docker:
    needs:
      - checks
      - unit-tests
      - integration-tests
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    uses: mia-platform/cdn-publish/.github/workflows/release-docker.yml@main
    with:
      version: latest
      push: true
    secrets:
      username: ${{ secrets.BOT_DOCKER_USERNAME }}
      token: ${{ secrets.BOT_DOCKER_TOKEN }}
