name: Install

on:
  workflow_call:
    inputs:
      node-version:
        default: 18.x
        required: false
        type: string
      context:
        default: ./
        required: false
        type: string

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true

      - name: Build Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-cache
        with:
          path: |
            ./dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build
