name: Pull request on Main

env:
  context: "./"
  cache-name: cache-release
  node-version: 18.x

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: mia-platform/cdn-publish/.github/workflows/prepare.yml@main

  checks:
    needs:
      - prepare
    uses: mia-platform/cdn-publish/.github/workflows/checks.yml@main

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    needs:
      - prepare
    uses: mia-platform/cdn-publish/.github/workflows/unit-tests.yml@main
    with:
      node-version: ${{ matrix.node-version }}

  integration-tests:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    needs:
      - prepare
    uses: mia-platform/cdn-publish/.github/workflows/integration-tests.yml@main
    with:
      node-version: ${{ matrix.node-version }}
    secrets:
      storage_access_key: ${{ secrets.CDN_STORAGE_ACCESS_KEY }}
      storage_zone_name: ${{ secrets.CDN_STORAGE_ZONE_NAME }}
      storage_base_url: ${{ secrets.CDN_STORAGE_BASE_URL }}
