name: Docker container release

on:
  workflow_call:
    inputs:
      push:
        default: false
        required: false
        type: boolean
      node-version:
        default: 18.x
        required: false
        type: string
      version:
        required: true
        type: string
    secrets:
      username:
        required: true
      token:
        required: true

jobs:
  release-docker:
    name: Build web-server docker container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true

      - name: Install
        run: yarn install --immutable

      - name: Build Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-cache
        with:
          path: |
            ./dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Prepare
        id: prepare-docker-container
        run: |
          DOCKER_IMAGE=miaplatform/cdn-publish
          echo "tag=${DOCKER_IMAGE}:${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: Build and push
        if: ${{ inputs.push }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./
          file: ./.docker/Dockerfile
          build-args: |
            COMMIT_SHA=${GITHUB_SHA}
            VERSION=${{ inputs.version }}
          push: true
          tags: ${{ steps.prepare-docker-container.outputs.tag }}
