name: Unit Tests

on:
  workflow_call:
    inputs:
      node-version:
        default: 18.x
        required: false
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true

      - name: Install
        run: yarn install --immutable

      - name: Run unit tests
        run: yarn coverage

      - name: "Upload Artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage
          path: coverage/cobertura-coverage.xml
